// <auto-generated />
using System;
using System.Data.Entity.Spatial;
using SalesCustomer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SalesCustomer.Migrations
{
    [DbContext(typeof(SalesCustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SalesCustomers.Models.SalesCustomers", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"), 1L, 1);

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BillToCustomerID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerCategoryID")
                     .HasColumnType("int");

                    b.Property<int>("BuyingGroupID")
                     .HasColumnType("int");
                    b.Property<int>("PrimaryContactPersonID")
.HasColumnType("int");

                    b.Property<int>("AlternateContactPersonI")
                     .HasColumnType("int");

                    b.Property<int>("DeliveryMethodID")
                     .HasColumnType("int");


                    b.Property<int>("DeliveryCityID")
                .HasColumnType("int");

                    b.Property<int>("PostalCityID")
                .HasColumnType("int");

                    b.Property<decimal>("CreditLimit")
                .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("AccountOpenedDate")
                 .HasColumnType("date");

                    b.Property<decimal>("StandardDiscountPercentage")
    .HasColumnType("decimal(18, 3)");

                    b.Property<bool>("IsStatementSent")
                   .HasColumnType("bit");

                    b.Property<bool>("IsOnCreditHold")
                 .HasColumnType("bit");

                    b.Property<int>("PaymentDays")
              .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
              .HasColumnType("nvarchar(20)");

                    b.Property<string>("FaxNumber")
       .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryRun")
.HasColumnType("nvarchar(5)");

                    b.Property<string>("RunPosition")
.HasColumnType("nvarchar(5)");

                    b.Property<string>("WebsiteURL")
.HasColumnType("nvarchar(256)");


                    b.Property<string>("DeliveryAddressLine1")
.HasColumnType("nvarchar(60)");

                    b.Property<string>("DeliveryAddressLine2")
.HasColumnType("nvarchar(60)");

                    b.Property<string>("DeliveryPostalCode")
.HasColumnType("nvarchar(60)");


                    b.Property<string>("PostalAddressLine1")
.HasColumnType("nvarchar(60)");

                    b.Property<string>("PostalAddressLine2")
.HasColumnType("nvarchar(60)");

                    b.Property<string>("PostalPostalCode")
.HasColumnType("nvarchar(10)");

                    b.Property<int>("LastEditedBy")
        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
.HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
.HasColumnType("datetime2");

                    b.HasKey("CustomerID");

                    b.ToTable("Sales.Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
